// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmOHZ8nCdn9BTKgt1ztgmW3j5yYuvSRU',
    appId: '1:318426567786:web:2dd567401cc3bb56c3e613',
    messagingSenderId: '318426567786',
    projectId: 'food-delivery-app-de790',
    authDomain: 'food-delivery-app-de790.firebaseapp.com',
    storageBucket: 'food-delivery-app-de790.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVXp765_L7W25hmh293JhzM3AoRmsvmc',
    appId: '1:318426567786:android:cd99ac02bca3bc4bc3e613',
    messagingSenderId: '318426567786',
    projectId: 'food-delivery-app-de790',
    storageBucket: 'food-delivery-app-de790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQuDS19SBqOmCmA7AUzgNdzqVC4PF4cw',
    appId: '1:318426567786:ios:398197f1121418fac3e613',
    messagingSenderId: '318426567786',
    projectId: 'food-delivery-app-de790',
    storageBucket: 'food-delivery-app-de790.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyQuDS19SBqOmCmA7AUzgNdzqVC4PF4cw',
    appId: '1:318426567786:ios:398197f1121418fac3e613',
    messagingSenderId: '318426567786',
    projectId: 'food-delivery-app-de790',
    storageBucket: 'food-delivery-app-de790.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLmOHZ8nCdn9BTKgt1ztgmW3j5yYuvSRU',
    appId: '1:318426567786:web:44c6155a21333643c3e613',
    messagingSenderId: '318426567786',
    projectId: 'food-delivery-app-de790',
    authDomain: 'food-delivery-app-de790.firebaseapp.com',
    storageBucket: 'food-delivery-app-de790.firebasestorage.app',
  );
}
